export const Industries = [
  { _id: 1, key: 'Technology', label: 'Technology' },
  { _id: 2, key: 'Software', label: 'Software & SaaS' },
  { _id: 3, key: 'Finance', label: 'Finance & Banking' },
  { _id: 4, key: 'Insurance', label: 'Insurance' },
  { _id: 5, key: 'FinTech', label: 'FinTech' },
  { _id: 6, key: 'Healthcare', label: 'Healthcare' },
  { _id: 7, key: 'Pharmaceuticals', label: 'Pharmaceuticals' },
  { _id: 8, key: 'Biotechnology', label: 'Biotechnology' },
  { _id: 9, key: 'Education', label: 'Education' },
  { _id: 10, key: 'ECommerce', label: 'E-Commerce' },
  { _id: 11, key: 'Retail', label: 'Retail' },
  { _id: 12, key: 'Manufacturing', label: 'Manufacturing' },
  { _id: 13, key: 'Construction', label: 'Construction' },
  { _id: 14, key: 'RealEstate', label: 'Real Estate' },
  { _id: 15, key: 'Transportation', label: 'Transportation & Logistics' },
  { _id: 16, key: 'Automotive', label: 'Automotive' },
  { _id: 17, key: 'Energy', label: 'Energy & Utilities' },
  { _id: 18, key: 'OilAndGas', label: 'Oil & Gas' },
  { _id: 19, key: 'Telecommunications', label: 'Telecommunications' },
  { _id: 20, key: 'Media', label: 'Media & Entertainment' },
  { _id: 21, key: 'Hospitality', label: 'Hospitality & Tourism' },
  { _id: 22, key: 'Agriculture', label: 'Agriculture' },
  { _id: 23, key: 'Government', label: 'Government & Public Sector' },
  { _id: 24, key: 'NonProfit', label: 'Non-Profit / NGO' },
  { _id: 25, key: 'ProfessionalServices', label: 'Professional Services' }
];